package com.qutalk.mall.db.dao;

import com.qutalk.mall.db.domain.CouponCate;
import com.qutalk.mall.db.domain.CouponCateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    long countByExample(CouponCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int deleteByExample(CouponCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int insert(CouponCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int insertSelective(CouponCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CouponCate selectOneByExample(CouponCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CouponCate selectOneByExampleSelective(@Param("example") CouponCateExample example, @Param("selective") CouponCate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CouponCate> selectByExampleSelective(@Param("example") CouponCateExample example, @Param("selective") CouponCate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    List<CouponCate> selectByExample(CouponCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CouponCate selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CouponCate.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    CouponCate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CouponCate record, @Param("example") CouponCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CouponCate record, @Param("example") CouponCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_cate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponCate record);
}