package com.qutalk.mall.db.dao;

import com.qutalk.mall.db.domain.Pptm;
import com.qutalk.mall.db.domain.PptmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PptmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    long countByExample(PptmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int deleteByExample(PptmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int insert(Pptm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int insertSelective(Pptm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pptm selectOneByExample(PptmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pptm selectOneByExampleSelective(@Param("example") PptmExample example, @Param("selective") Pptm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Pptm> selectByExampleSelective(@Param("example") PptmExample example, @Param("selective") Pptm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    List<Pptm> selectByExample(PptmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Pptm selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Pptm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    Pptm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Pptm record, @Param("example") PptmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Pptm record, @Param("example") PptmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Pptm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pptm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Pptm record);
}