spring:
  profiles:
    active: db
  message:
    encoding: UTF-8

logging:
  level:
    root:  info
    org.springframework:  ERROR
    org.mybatis:  info
    com.qutalk.mall.db:  info
  path: /opt/logs
  file: qutalkmall.log