spring:
  profiles:
    active: db, core, wx
  message:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  info
    org.springframework:  ERROR
    org.mybatis:  info
    com.qutalk.mall.wx:  info
    com.qutalk.mall:  infocp
  path: /opt/qutalkmall
  file: server.log